config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy] # comented section use for specific route
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

  get   'password/reset', to: 'password_resets#new', as: 'new_password_reset'
  post  'password/reset', to: 'password_resets#create', as: 'password_reset'
  get   'password/reset/edit', to: 'password_resets#edit', as: 'edit_password_reset'
  patch 'password/reset/edit', to: 'password_resets#update', as: 'update_password_reset'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1500 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # this remove code retendency
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy] 

  def show
    #binding.break # In Rails 6 this is byebug this use for debug
  end

  def index
    # @articles = Article.paginate(page: params[:page], per_page: 5)
    # iteam is define no. of iteam per page 
    @pagy, @articles = pagy(Article.all, items: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created sucessfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated sucessfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  # use private for prevent access method outside of this controller
  private

  # Use this for remove code retendency

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end


end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header fst-italic ">
              <% if article.user %>
                by <%= link_to article.user.username, user_path(article.user), class: "text-decoration-none" %>
              <% end %>

              <% if article.categories.any? %>
                <div class="mt-2"><%= render article.categories %></div>
              <% end %>

            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success", style: "text-decoration: none;" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                  <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
                  <%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago, Edited <%= time_ago_in_words(article.updated_at) %> ago </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container ">

  <div class="row justify-content-center">

    <!-- show errors by render errors from shared folder  -->
    <%= render 'shared/errors', obj: @article %>

    <!-- Form for submit title and description -->
    <%= form_with(model: @article, class: "shadow p-3 mb-3  rounded", local: true, data: {turbo: false })  do |f| %>

      <div class="mb-3 row">
        <%= f.label :title, class: "col-sm-2 col-form-label fw-bold" %>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Article" %>
        </div>
      </div>

      <div class="mb-3 row">
        <%= f.label :description, class: "col-sm-2 col-form-label fw-bold" %>
        <div class="col-sm-10">
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of Article" %>
        </div>
      </div>

      <div class="mb-3 row">
        <%= f.label :category, class: "col-sm-2 col-form-label fw-bold" %>
        <div class="col-sm-10">
          <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selection from the list below(can be empty)"}, { multiple: true, size: 3, class: "form-select shadow rounded" })%>
        </div>
      </div>

      <div class="mb-3 row justify-content-center">
        <div class="col-8">
          <%= f.submit class: "btn btn-outline-success btn-lg " %>
        </div>
      </div>

      <div class="mb-3 row justify-content-center">
        <div class="col-8">
          <%= link_to 'Return 🔙 to Articles listing', articles_path, class: "btn btn-outline-primary btn-lg" %>
        </div>
      </div>

    </div>
    <% end %>

</div>

app/views/articles/edit.html.erb
  <h1 class="text-center pt-4">Edit Article</h1>

  <!-- render form from _form.html.erb(partial form)  -->
  <%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center pt-4">Listing all Articles</h1>

<!-- add pagination  -->
<% if Article.count > 5 %>
  <div class="pagination-container">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>

<%= render 'article' %>

<% if @articles.size > 4 %>
  <div class="pagination-container">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center pt-4">Create a New Article</h1>

<!-- render form from _form.html.erb(partial form)  -->
<%= render 'form' %>

app/views/articles/show.html.erb
<!-- Show a Article Page -->
<h2 class="text-center pt-4"> <%= @article.title %> </h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to avatar_for(@article.user), user_path(@article.user) %>

          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>

        </div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, Edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
        </div>
        <div class="card-footer">
          <% if logged_in? %>
            <%= link_to '➕ 🆕 Article', new_article_path, class: "btn btn-outline-primary btn-md" %>
          <% end %>
          <%= link_to 'Return 🔙 to Articles listing', articles_path, class: "btn btn-outline-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>