config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy] # comented section use for specific route
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

  get   'password/reset', to: 'password_resets#new', as: 'new_password_reset'
  post  'password/reset', to: 'password_resets#create', as: 'password_reset'
  get   'password/reset/edit', to: 'password_resets#edit', as: 'edit_password_reset'
  patch 'password/reset/edit', to: 'password_resets#update', as: 'update_password_reset'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was sucessfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated sucessfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @pagy, @categories = pagy(Category.all, items: 5)
  end

  def show
   @category = Category.find(params[:id])
   @pagy, @articles = pagy(@category.articles, items: 3)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge text-bg-secondary me-1 text-decoration-none" %>

app/views/categories/_form.html.erb
<div class="row mb-3 container justify-content-center">
  <div class="col-sm-8">
  <!-- show errors by render errors from shared folder  -->
  <%= render 'shared/errors', obj: @category %>
  </div>
</div>

<!-- Form for submit Category name -->
<%= form_with(model: @category, local: true, data: {turbo: false })  do |f| %>

  <div class="mb-3 row ">
    <%= f.label :name, "Category Name:", class: "col-sm-2 col-form-label fw-bold" %>
    <div class="col-sm-5">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter Category Name" %>
    </div>
  </div>

  <div class="mb-3 row ">
    <div class="col-6">
      <%= f.submit class: "btn btn-outline-success btn-lg" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center pt-4">Edit Category Name</h1>

<div class="container text-center w-75 shadow p-3 mb-3  rounded">
  <div class="row  justify-content-center ">
    <%= render 'form' %>

    <div class="mb-3">
      <div class="col-7">
        <%= link_to "Cancle and Return 🔙 to #{@category.name}", category_path(@category), class: "btn btn-outline-primary btn-lg" %>
      </div>
    </div>

  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center pt-4">Categories</h1>

<!-- add pagination  -->
<!-- This pagination automatic dessapper when count is less then 5 -->
<% if @total_categories = Category.count > 5 %>
  <div class="pagination-container">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success", style: "text-decoration: none;" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, Edited <%= time_ago_in_words(category.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!-- add pagination  -->
<!-- This pagination automatic dessapper when this page has less then 4 categories -->
<% if @categories.count > 4 %>
  <div class="pagination-container">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1 class="text-center pt-4">Create a new Category</h1>

<div class="container text-center w-75 shadow p-3 mb-3  rounded">
  <div class="row  justify-content-center ">
    <%= render 'form' %>

    <div class="mb-3">
      <div class="col-8">
        <%= link_to 'Cancle and Return to Category listing', categories_path, class: "btn btn-outline-primary btn-lg" %>
      </div>
    </div>

  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center pt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center pt-4">
    <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center pt-4">Articles</h3>

  <% if @category.articles.count > 3 %>
    <div class="pagination-container">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  <% end %>

  <% if @category.articles.empty? %>
    <!-- Print message if the category has no articles -->
    <h3 class="text-center pt-4">This category doesn't have any articles.</h3>
  <% else %>
    <!-- Print articles if the category has articles -->
    <%= render 'articles/article' %>
  <% end %>

  <% if @articles.count >= 3 %>
    <div class="pagination-container">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  <% end %>