config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy] # comented section use for specific route
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

  get   'password/reset', to: 'password_resets#new', as: 'new_password_reset'
  post  'password/reset', to: 'password_resets#create', as: 'password_reset'
  get   'password/reset/edit', to: 'password_resets#edit', as: 'edit_password_reset'
  patch 'password/reset/edit', to: 'password_resets#update', as: 'update_password_reset'
end

app/views/layouts/_footer.html.erb
 <!-- Footer's code -->
<!-- <div class=" d-flex flex-column"> -->
  <footer id="sticky-footer" class="flex-shrink-0 py-3 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Ram Gopal", "https://ramgopal.dev/", class: "text-white " %> </small>
    <!-- </div> -->
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container mt-5 ">
  <% flash.each do |name, msg| %>
    <div class="alert <%= (name == "alert") ? "alert-danger" : "alert-success" %> </div> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu">
                <% if logged_in? && current_user.admin? %>
                  <li><%= link_to "➕ 🆕 Categories", new_category_path, class: "dropdown-item" %></li>
                  <% end %>
                <li><%= link_to "View Categories", categories_path, class: "dropdown-item" %></li>
              </ul>
          </li>

          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "➕ 🆕 Article", new_article_path, class: "nav-link" %>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Your Profile", user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "Edit Your Profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "Delete Your Profile", user_path(current_user), class: "dropdown-item text-danger", data: {turbo_method: :delete, "turbo-confirm": "Are you sure? All your Articles and Account info will be deleted as well"}%></li>
              </ul>
            </li>

            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", data: {turbo_method: :delete} %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", signup_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>

          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>

      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>AlphaBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application" , media: 'all' , "data-turbo-track"=> "reload" %>
  <%= stylesheet_link_tag "custom" , "data-turbo-track"=> "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <div class="d-flex flex-column min-vh-100">
    <div class="flex-grow-1">
      <!-- Your page content goes here -->
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <!-- Render Footer -->
    <%= render 'layouts/footer' %>
  </div>
</body>

</html>